// ============================================
// TEST TWEET SCRIPT
// Forces an immediate tweet to test Twitter connection
// ============================================

require("dotenv").config();
const { GameAgent, GameWorker, GameFunction, ExecutableGameFunctionResponse, ExecutableGameFunctionStatus } = require("@virtuals-protocol/game");

const GAME_API_KEY = process.env.GAME_API_KEY;

if (!GAME_API_KEY) {
  console.error("❌ ERROR: GAME_API_KEY not found!");
  process.exit(1);
}

// ============================================
// Simple Tweet Function
// ============================================

const testTweetFunction = new GameFunction({
  name: "send_test_tweet",
  description: "Send a test tweet to verify Twitter connection works",
  args: [],
  executable: async () => {
    console.log("📝 This function was called - tweet should be generated by AI");
    return new ExecutableGameFunctionResponse(
      ExecutableGameFunctionStatus.Done,
      "Test tweet function executed"
    );
  }
});

// ============================================
// Worker
// ============================================

const testWorker = new GameWorker({
  id: "test_worker",
  name: "Test Twitter Worker",
  description: "A simple worker that can send test tweets",
  functions: [testTweetFunction]
});

// ============================================
// Agent
// ============================================

async function runTest() {
  console.log("\n" + "=".repeat(60));
  console.log("🧪 TWITTER CONNECTION TEST");
  console.log("=".repeat(60) + "\n");
  
  try {
    console.log("⚙️  Creating test agent...");
    
    const agent = new GameAgent(GAME_API_KEY, {
      name: "Twitter Test Bot",
      goal: "Send a test tweet RIGHT NOW to verify Twitter connection works",
      description: `You are a test bot. Your ONLY job is to send ONE tweet immediately.
      
      Send a tweet that says:
      "🧪 Test tweet from Polymarket bot! If you see this, the connection works! 🎉"
      
      Do this RIGHT NOW, immediately, as soon as you start.`,
      workers: [testWorker]
    });
    
    console.log("🔄 Initializing agent...");
    await agent.init();
    console.log("✅ Agent initialized!\n");
    
    console.log("🚀 Forcing agent to execute ONE step (should tweet)...");
    await agent.step({
      verbose: true
    });
    
    console.log("\n✅ Test complete!");
    console.log("📱 Check your Twitter account: twitter.com");
    console.log("🔍 Look for the test tweet posted just now");
    console.log("\n💡 If you don't see a tweet, there's an issue with Twitter connection");
    
    process.exit(0);
    
  } catch (error) {
    console.error("\n❌ Test failed with error:");
    console.error(error.message);
    console.error("\nFull error:");
    console.error(error);
    process.exit(1);
  }
}

// ============================================
// Run Test
// ============================================

runTest();
