name: Deploy Wisdom Tracker to Railway

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      
      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'
          cache: 'npm'
      
      - name: Install dependencies
        run: npm install
      
      - name: Run tests
        run: npm test
      
      - name: Lint code (if linter added)
        run: echo "No linter configured yet"

  deploy:
    needs: test
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/main'
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      
      - name: Deploy to Railway
        run: echo "Railway auto-deploys when connected to GitHub"
      
      # Railway automatically deploys when you push to main
      # No additional steps needed if Railway is connected to your repo
      
      - name: Deployment Status
        run: |
          echo "✅ Code pushed to main branch"
          echo "🚂 Railway will auto-deploy"
          echo "📊 Check Railway dashboard for status"